### ISSUE TITLE
Implement initial brushstroke-container 

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/brushstroke-container#1]
## Summary

Implement the initial Docker container for the Neural Brushstroke Engine.

## Tasks

- [ ] Create Dockerfile
  - Use Python base image
  - Install PyTorch and other dependencies
  - Copy Neural Brushstroke Engine code
- [ ] Create entrypoint script
  - Start Flask server for UI
- [ ] Copy pretrained models
- [ ] Configure environment variables
  - MODEL - Which model to use 
  - PORT - Port for Flask server
- [ ] Write README
  - Overview
  - Usage
  - Models

## Requirements

- Dockerfile builds image with Neural Brushstroke Engine
- Entrypoint launches drawing UI server
- Pretrained models included
- README explains usage and configuration

## Resources

- Neural Brushstroke Engine repo: https://github.com/nv-tlabs/brushstroke_engine
- Flask UI code: https://github.com/nv-tlabs/brushstroke_engine/tree/master/forger/ui
- Models: https://drive.google.com/drive/folders/1Ao-3LZPmOSCZA7GIm5piQ3T6PK63NCZe
